name: run test cases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Give permissions to workspace
        run: sudo chmod -R ugo+rwx ${{ github.workspace }}

      - name: Print GITHUB_TOKEN (obfuscated)
        run: |
          echo "GITHUB_TOKEN starts with: ${GITHUB_TOKEN:0:4}********"

      - name: Restore Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run the test cases using Docker Compose
        run: |
          docker-compose down --volumes --remove-orphans
          docker-compose up --abort-on-container-exit

      - name: Save Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Publish JUnit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "**/surefire-reports/TEST-*.xml"

      - name: Cleanup Docker
        if: always()
        run: |
          docker-compose down --volumes --remove-orphans
          docker system prune -f --volumes
